# Generated by Django 4.0.4 on 2022-07-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomiyArizasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shaxs_turi', models.CharField(choices=[('Jismoniy shaxs', 'Jismoniy shaxs'), ('Yuridik shaxs', 'Yuridik shaxs')], default='None', max_length=20)),
                ('Ismi', models.CharField(default='nomalum', max_length=100)),
                ('Telefon_raqami', models.DecimalField(decimal_places=0, max_digits=78)),
                ('tulov_suma', models.CharField(choices=[('None', 'Boshqa'), ('1 000 000 uzs', '1 000 000 uzs'), ('5 000 000 uzs', '5 000 000 uzs'), ('7 000 000 uzs', '7 000 000 uzs'), ('10 000 000 uzs', '10 000 000 uzs'), ('30 000 000 uzs', '30 000 000 uzs')], default='Tanlanmadi', max_length=30)),
                ('boshqa_suma', models.IntegerField(default='0', null=True)),
                ('tashkilot_nomi_yuridik_uchun', models.CharField(default='no_company', max_length=100)),
                ('ariza_holati', models.CharField(choices=[('Tasdiqlanmagan', 'Tasdiqlanmagan'), ('Tasdiqlandi', 'Tasdiqlandi')], default='Tasdiqlangani yuq', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='LibUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TalabaQushish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talaba_F_I_SH', models.CharField(default='None', max_length=200)),
                ('telefon_raqami', models.DecimalField(decimal_places=0, max_digits=78)),
                ('OTM_ruyhati', models.CharField(choices=[('OTM example', 'OTM example')], default='Tanlanmadi', max_length=200)),
                ('Talabalik_turi', models.CharField(choices=[('Barchasi', 'Barchasi'), ('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr')], default='Tanlanmadi', max_length=200)),
                ('Kontrakt_summa', models.DecimalField(decimal_places=0, max_digits=178)),
                ('Ajratilgn_summa', models.DecimalField(decimal_places=0, default='0', max_digits=178)),
            ],
        ),
        migrations.CreateModel(
            name='HomiyQushish_Talabaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beradigan_summa', models.DecimalField(decimal_places=0, default='0', max_digits=178)),
                ('homiy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mov.homiyarizasi')),
                ('talaba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mov.talabaqushish')),
            ],
        ),
    ]
