# Generated by Django 4.0.4 on 2022-07-19 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0002_alter_homiyqushish_talabaga_homiy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiyqushish_talabaga',
            name='homiy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mov.homiyarizasi'),
        ),
    ]
