# Generated by Django 4.0.4 on 2022-07-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0003_alter_homiyqushish_talabaga_homiy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homiyqushish_talabaga',
            name='talaba',
        ),
        migrations.AlterField(
            model_name='homiyarizasi',
            name='tulov_suma',
            field=models.CharField(choices=[('None', 'Boshqa'), (1000000, 1000000), (5000000, 5000000), (7000000, 7000000), (10000000, 10000000), (30000000, 30000000)], default='Tanlanmadi', max_length=30),
        ),
    ]
