# Generated by Django 4.0.4 on 2022-07-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mov', '0006_remove_homiyarizasi_boshqa_suma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homiyarizasi',
            name='Balans',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=78),
        ),
    ]
